# Generated by Django 4.0 on 2021-12-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpscaledImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('filename', models.CharField(max_length=80)),
                ('lr_image', models.ImageField()),
                ('hr_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
